Improve will message
emqx/emqx-delayed-publish pull request #6
Opened 2018-10-09 05:53 UTC by tigercl

If a new Network Connection to this Session is made before the Will Delay Interval has passed, the Server MUST NOT send the Will Message.

2018-10-18 15:38 UTC, spring2maz commented on src/emqx_delayed_publish.erl
> +on_message_publish(Msg = #message{topic = <<"$delayed/", Topic/binary>>}) ->
worth introducing a macro for `$delayed` like `$queue` and `$share`, see `emqx.hrl`

2018-10-18 15:41 UTC, spring2maz commented on src/emqx_delayed_publish.erl
> +on_message_publish(Msg = #message{topic = <<"$will/", Topic/binary>>, headers = #{client_id := ClientId}}) ->
and for `$will` too.

2018-10-18 15:42 UTC, spring2maz commented on src/emqx_delayed_publish.erl
> +                        end, WillMsgs),
align with `fun`
and indent more for function body.

2018-10-18 15:48 UTC, spring2maz commented on src/emqx_delayed_publish.erl
> +handle_message(ClientId, Delay, Msg = #message{id = Id, timestamp = Ts}) ->
IMHO. a better abstraction is to move he Delay or Timestamp logic to a separate function (which can be easily eunit-tested).
But not to make a higer level abstraction as `handle_message`
i.e. the `ok = store(...),` call can be kept at its old place, so the return value  `{stop, Msg}` tuple do not have to be scattered into multiple functions.

2018-10-23 17:28 UTC, terry-xiaoyu requested changes

2018-10-23 17:28 UTC, terry-xiaoyu commented on src/emqx_delayed_publish.erl
> +delay_publish(Msg = #message{id = Id, timestamp = Ts, headers = #{'Will-Delay-Interval' := Interval}}, ClientId) ->
The API can not be like this.. A better design is to keep the isolation of the components. Don't depends on the internal 'Will-Delay-Interval' for the delay interval.
e.g.
`delay_publish(Msg, ID, {secs, DelaySeconds}) -> ok.`
`delay_publish(Msg, ID, {ts, Timestamp}) -> ok.`
`cancel_publish(Msg, ID) -> ok.`

2018-10-23 17:28 UTC, terry-xiaoyu commented on src/emqx_delayed_publish.erl
> -    {ok, Msg}.
The $delay should be kept. It is for user to publish delayed msgs via prefixed topics. 
We also need to add another prefixed topic for canceling previous published delay messages, just like the function APIs.

e.g. We may need to change the prefixed topics like this:

`$delay/<Interval or timestamp>/<id>/topic`
`$cancel_delay/<id>`

2018-10-23 17:28 UTC, terry-xiaoyu commented on src/emqx_delayed_publish.erl
> +            Result = lists:keysearch(mnesia:dirty_first(?TAB), 2, WillMsgs),
Change the mnesia type from `set` to `ordered_set`, or this `first .. next` iteration on a set ets table will not work as expected, as set tables are not sorted in the order of insertion.

2018-10-23 17:28 UTC, terry-xiaoyu commented on src/emqx_delayed_publish.erl
> +cancel_publish(ClientId) ->
Not `ClientID`, should be `ID`. User specifies a message id for its delayed message when calling this API.

2018-10-25 08:37 UTC, closed without merging